version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=barter_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # Сервис Redis для кэширования
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Основное Django приложение
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=barter_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  # Celery worker для асинхронных задач (опционально)
  celery:
    build: .
    command: celery -A barter_platform worker -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-your-secret-key-here
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=barter_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data: