# Generated by Django 4.2.7 on 2025-05-27

from django.db import migrations, models
import apps.ads.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара (максимум 5MB)', null=True, upload_to=apps.ads.models.ad_image_upload_path, verbose_name='Изображение'),
        ),
    ]